# Generated by Django 3.2.8 on 2022-03-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220325_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Testimonial'),
        ),
    ]
