# Generated by Django 3.2.8 on 2022-03-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220325_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
